import type { ChartOutputFormat, TemplateStatus } from "./types";

export type ChartFamily =
  | "基础比较"
  | "趋势与关系"
  | "分布"
  | "组成"
  | "矩阵与层级"
  | "空间与网络"
  | "高级图"
  | "流向图"
  | "表格与集合"
  | "sankey"
  | "table";

export interface ChartTemplate {
  id: string;
  name: string;
  family: ChartFamily;
  description: string;
  kind: string;
  needs?: string[];
  /** 图标语义；图标本地渲染，离线也可用。 */
  icon: ChartIcon;
  /** R Graph Gallery 对应图表类型的参考页。 */
  galleryUrl: string;
  status: TemplateStatus;
  sourceRepoPath?: string;
  packages: string[];
  outputs: ChartOutputFormat[];
}

export type ChartIcon =
  | "bar"
  | "line"
  | "scatter"
  | "distribution"
  | "pie"
  | "matrix"
  | "map"
  | "network"
  | "radar";

const galleryUrlFor = (kind: string) => {
  const section: Record<string, string> = {
    bar: "barplot",
    stacked_bar: "barplot",
    lollipop: "lollipop-plot",
    dot: "barplot",
    line: "line-plot",
    area: "area-chart",
    regression: "scatterplot",
    scatter: "scatterplot",
    bubble: "bubble-chart",
    histogram: "histogram",
    density: "density-plot",
    violin: "violin",
    boxplot: "boxplot",
    stripchart: "beeswarm",
    pie: "pie-plot",
    heatmap: "heatmap",
    dendrogram: "dendrogram",
    network: "network",
    radar: "spider-or-radar-chart",
    parallel: "parallel-plot",
    venn: "venn-diagram",
  };
  return `https://r-graph-gallery.com/${section[kind] ?? ""}.html`;
};

const iconFor = (kind: string): ChartIcon => {
  if (["bar", "stacked_bar", "lollipop", "dot"].includes(kind)) return "bar";
  if (["line", "area", "regression", "parallel"].includes(kind)) return "line";
  if (["scatter", "bubble"].includes(kind)) return "scatter";
  if (["histogram", "density", "violin", "boxplot", "stripchart"].includes(kind))
    return "distribution";
  if (["pie"].includes(kind)) return "pie";
  if (["heatmap", "dendrogram"].includes(kind)) return "matrix";
  if (["network"].includes(kind)) return "network";
  if (["radar", "venn"].includes(kind)) return "radar";
  return "map";
};

// 对应 R Graph Gallery 的常用图形入口；每项都有可运行示例和同一套易懂参数。
const officialTemplates: ChartTemplate[] = [
  {
    id: "bar-basic-ggplot2",
    name: "基础柱状图",
    family: "基础比较",
    description: "R Graph Gallery 的 ggplot2 基础柱状图",
    kind: "bar",
    icon: "bar",
    galleryUrl: "https://r-graph-gallery.com/218-basic-barplots-with-ggplot2.html",
    status: "verified",
    sourceRepoPath: "218-basic-barplots-with-ggplot2.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "line-basic-ggplot2",
    name: "基础折线图",
    family: "趋势与关系",
    description: "R Graph Gallery 的 ggplot2 基础折线图",
    kind: "line",
    icon: "line",
    galleryUrl: "https://r-graph-gallery.com/279-plotting-time-series-with-ggplot2.html",
    status: "verified",
    sourceRepoPath: "279-plotting-time-series-with-ggplot2.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "scatter-basic-ggplot2",
    name: "基础散点图",
    family: "趋势与关系",
    description: "R Graph Gallery 的 ggplot2 基础散点图",
    kind: "scatter",
    icon: "scatter",
    galleryUrl: "https://r-graph-gallery.com/272-basic-scatterplot-with-ggplot2.html",
    status: "verified",
    sourceRepoPath: "272-basic-scatterplot-with-ggplot2.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "histogram-basic-ggplot2",
    name: "基础直方图",
    family: "分布",
    description: "R Graph Gallery 的 ggplot2 基础直方图",
    kind: "histogram",
    icon: "distribution",
    galleryUrl: "https://r-graph-gallery.com/220-basic-ggplot2-histogram.html",
    status: "verified",
    sourceRepoPath: "220-basic-ggplot2-histogram.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "boxplot-basic-ggplot2",
    name: "基础箱线图",
    family: "分布",
    description: "R Graph Gallery 的 ggplot2 基础箱线图",
    kind: "boxplot",
    icon: "distribution",
    galleryUrl: "https://r-graph-gallery.com/262-basic-boxplot-with-ggplot2.html",
    status: "verified",
    sourceRepoPath: "262-basic-boxplot-with-ggplot2.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "density-basic-ggplot2",
    name: "基础密度图",
    family: "分布",
    description: "R Graph Gallery 的 ggplot2 密度图",
    kind: "density",
    icon: "distribution",
    galleryUrl: "https://r-graph-gallery.com/density-plot.html",
    status: "verified",
    sourceRepoPath: "density-plot.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "violin-basic-ggplot2",
    name: "基础小提琴图",
    family: "分布",
    description: "R Graph Gallery 的 ggplot2 小提琴图",
    kind: "violin",
    icon: "distribution",
    galleryUrl: "https://r-graph-gallery.com/violin.html",
    status: "verified",
    sourceRepoPath: "violin-plot.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "pie-basic-ggplot2",
    name: "基础饼图",
    family: "组成",
    description: "R Graph Gallery 的 ggplot2 饼图",
    kind: "pie",
    icon: "pie",
    galleryUrl: "https://r-graph-gallery.com/pie-plot.html",
    status: "verified",
    sourceRepoPath: "pie-chart.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "heatmap-basic-ggplot2",
    name: "基础热图",
    family: "矩阵与层级",
    description: "R Graph Gallery 的 ggplot2 热图",
    kind: "heatmap",
    icon: "matrix",
    galleryUrl: "https://r-graph-gallery.com/heatmap.html",
    status: "verified",
    sourceRepoPath: "heatmap.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "radar-basic-ggplot2",
    name: "基础雷达图",
    family: "高级图",
    description: "R Graph Gallery 风格的基础雷达图",
    kind: "radar",
    icon: "radar",
    galleryUrl: "https://r-graph-gallery.com/spider-or-radar-chart.html",
    status: "verified",
    sourceRepoPath: "radar-chart.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "area-basic-ggplot2",
    name: "基础面积图",
    family: "趋势与关系",
    description: "R Graph Gallery 的基础面积图",
    kind: "area",
    icon: "line",
    galleryUrl: "https://r-graph-gallery.com/area-chart.html",
    status: "verified",
    sourceRepoPath: "area-chart.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "regression-basic-ggplot2",
    name: "回归散点图",
    family: "趋势与关系",
    description: "散点与线性趋势带",
    kind: "regression",
    icon: "scatter",
    galleryUrl: "https://r-graph-gallery.com/scatterplot.html",
    status: "verified",
    sourceRepoPath: "scatter-plot.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "lollipop-basic-ggplot2",
    name: "棒棒糖图",
    family: "基础比较",
    description: "以简洁线段展示类别排名",
    kind: "lollipop",
    icon: "bar",
    galleryUrl: "https://r-graph-gallery.com/lollipop-plot.html",
    status: "verified",
    sourceRepoPath: "lollipop-plot.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "donut-basic-ggplot2",
    name: "环形图",
    family: "组成",
    description: "饼图的中空版本，便于放置中心说明",
    kind: "donut",
    icon: "pie",
    galleryUrl: "https://r-graph-gallery.com/doughnut-plot.html",
    status: "verified",
    sourceRepoPath: "donut-plot.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "circular-bar-basic-ggplot2",
    name: "圆形柱状图",
    family: "高级图",
    description: "沿圆周排列的类别柱状图",
    kind: "circular_bar",
    icon: "bar",
    galleryUrl: "https://r-graph-gallery.com/circular-barplot.html",
    status: "verified",
    sourceRepoPath: "circular-barplot.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "grouped-bar-basic-ggplot2",
    name: "分组柱状图",
    family: "基础比较",
    description: "用颜色区分多个分组的柱状图",
    kind: "grouped_bar",
    icon: "bar",
    galleryUrl: "https://r-graph-gallery.com/barplot.html",
    status: "verified",
    sourceRepoPath: "grouped-barplot.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "stacked-bar-basic-ggplot2",
    name: "堆叠柱状图",
    family: "基础比较",
    description: "展示总量与分组构成",
    kind: "stacked_bar",
    icon: "bar",
    galleryUrl: "https://r-graph-gallery.com/stacked-barplot.html",
    status: "verified",
    sourceRepoPath: "stacked-barplot.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "bubble-basic-ggplot2",
    name: "气泡图",
    family: "趋势与关系",
    description: "以点大小表示第三个数值维度",
    kind: "bubble",
    icon: "scatter",
    galleryUrl: "https://r-graph-gallery.com/bubble-chart.html",
    status: "verified",
    sourceRepoPath: "bubble-chart.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "correlogram-basic-ggplot2",
    name: "相关性矩阵",
    family: "矩阵与层级",
    description: "查看多个数值变量之间的相关关系",
    kind: "correlogram",
    icon: "matrix",
    galleryUrl: "https://r-graph-gallery.com/correlogram.html",
    status: "verified",
    sourceRepoPath: "correlogram.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "dendrogram-basic-ggplot2",
    name: "树状图",
    family: "矩阵与层级",
    description: "展示样本或变量的层级聚类结构",
    kind: "dendrogram",
    icon: "matrix",
    galleryUrl: "https://r-graph-gallery.com/dendrogram.html",
    status: "verified",
    sourceRepoPath: "dendrogram.Rmd",
    packages: [],
    outputs: ["png", "svg"],
  },
  {
    id: "parallel-basic-ggplot2",
    name: "平行坐标图",
    family: "高级图",
    description: "在多个指标轴上比较记录轮廓",
    kind: "parallel",
    icon: "line",
    galleryUrl: "https://r-graph-gallery.com/parallel-plot.html",
    status: "verified",
    sourceRepoPath: "parallel-plot.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "network-basic-ggplot2",
    name: "网络图",
    family: "空间与网络",
    description: "用节点和连线展示关系网络",
    kind: "network",
    icon: "network",
    galleryUrl: "https://r-graph-gallery.com/network.html",
    status: "verified",
    sourceRepoPath: "network.Rmd",
    packages: [],
    outputs: ["png", "svg"],
  },
  {
    id: "sankey-basic-ggplot2",
    name: "桑基图",
    family: "空间与网络",
    description: "展示分类之间的流向和规模",
    kind: "sankey",
    icon: "network",
    galleryUrl: "https://r-graph-gallery.com/sankey-diagram.html",
    status: "verified",
    sourceRepoPath: "sankey.Rmd",
    packages: ["ggalluvial"],
    outputs: ["png", "svg"],
  },
  {
    id: "chord-basic-ggplot2",
    name: "弦图",
    family: "空间与网络",
    description: "展示群组之间的双向联系",
    kind: "chord",
    icon: "network",
    galleryUrl: "https://r-graph-gallery.com/chord-diagram.html",
    status: "verified",
    sourceRepoPath: "chord-diagram.Rmd",
    packages: ["circlize"],
    outputs: ["png", "svg"],
  },
  {
    id: "map-points-basic-ggplot2",
    name: "经纬度点地图",
    family: "空间与网络",
    description: "在经纬度平面上展示点位和数值",
    kind: "map",
    icon: "map",
    galleryUrl: "https://r-graph-gallery.com/map.html",
    status: "verified",
    sourceRepoPath: "map.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "wordcloud-basic",
    name: "词云",
    family: "高级图",
    description: "按词频突出显示文本关键词",
    kind: "wordcloud",
    icon: "pie",
    galleryUrl: "https://r-graph-gallery.com/wordcloud.html",
    status: "verified",
    sourceRepoPath: "wordcloud.Rmd",
    packages: ["wordcloud"],
    outputs: ["png", "svg"],
  },
  {
    id: "venn-basic",
    name: "韦恩图",
    family: "高级图",
    description: "展示两个或三个集合的交集",
    kind: "venn",
    icon: "radar",
    galleryUrl: "https://r-graph-gallery.com/venn-diagram.html",
    status: "verified",
    sourceRepoPath: "venn-diagram.Rmd",
    packages: ["VennDiagram"],
    outputs: ["png", "svg"],
  },
  {
    id: "connected-scatter-basic-ggplot2",
    name: "连线散点图",
    family: "趋势与关系",
    description: "用路径连接散点，观察变化方向",
    kind: "connected_scatter",
    icon: "scatter",
    galleryUrl: "https://r-graph-gallery.com/connected-scatterplot.html",
    status: "verified",
    sourceRepoPath: "connected-scatter-plot.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "slope-basic-ggplot2",
    name: "斜率图",
    family: "趋势与关系",
    description: "比较同一对象在两个时点的变化",
    kind: "slope",
    icon: "line",
    galleryUrl: "https://r-graph-gallery.com/barplot.html",
    status: "verified",
    sourceRepoPath: "slope-chart.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "table-basic",
    name: "数据表",
    family: "矩阵与层级",
    description: "将数据表格导出为图片",
    kind: "table",
    icon: "matrix",
    galleryUrl: "https://r-graph-gallery.com/table.html",
    status: "verified",
    sourceRepoPath: "table.Rmd",
    packages: [],
    outputs: ["png", "svg"],
  },
  {
    id: "ridgeline-basic",
    name: "山脊图",
    family: "分布",
    description: "对比多个分组的分布形状",
    kind: "ridgeline",
    icon: "distribution",
    galleryUrl: "https://r-graph-gallery.com/ridgeline-plot.html",
    status: "verified",
    sourceRepoPath: "ridgeline-graph.Rmd",
    packages: ["ggridges"],
    outputs: ["png", "svg"],
  },
  {
    id: "beeswarm-basic",
    name: "蜂群图",
    family: "分布",
    description: "展示每个观测点并避免重叠",
    kind: "beeswarm",
    icon: "distribution",
    galleryUrl: "https://r-graph-gallery.com/beeswarm.html",
    status: "verified",
    sourceRepoPath: "beeswarm.Rmd",
    packages: ["ggbeeswarm"],
    outputs: ["png", "svg"],
  },
  {
    id: "waffle-basic",
    name: "华夫图",
    family: "组成",
    description: "用网格直观展示组成比例",
    kind: "waffle",
    icon: "pie",
    galleryUrl: "https://r-graph-gallery.com/waffle.html",
    status: "verified",
    sourceRepoPath: "waffle-chart.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "treemap-basic",
    name: "矩形树图",
    family: "组成",
    description: "按面积展示层级组成",
    kind: "treemap",
    icon: "matrix",
    galleryUrl: "https://r-graph-gallery.com/treemap.html",
    status: "verified",
    sourceRepoPath: "treemap.Rmd",
    packages: ["treemap"],
    outputs: ["png", "svg"],
  },
  {
    id: "alluvial-basic",
    name: "河流图",
    family: "流向图",
    description: "追踪多个阶段之间的分类流动",
    kind: "alluvial",
    icon: "network",
    galleryUrl: "https://r-graph-gallery.com/sankey-diagram.html",
    status: "verified",
    sourceRepoPath: "alluvial.Rmd",
    packages: ["ggalluvial"],
    outputs: ["png", "svg"],
  },
  {
    id: "upset-basic",
    name: "UpSet 集合图",
    family: "表格与集合",
    description: "比较多个集合的交集规模",
    kind: "upset",
    icon: "matrix",
    galleryUrl: "https://r-graph-gallery.com/upset-plot.html",
    status: "verified",
    sourceRepoPath: "upset.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "hexbin-basic",
    name: "六边形密度图",
    family: "空间与网络",
    description: "用六边形聚合大量散点",
    kind: "hexbin",
    icon: "matrix",
    galleryUrl: "https://r-graph-gallery.com/hexbin-map.html",
    status: "verified",
    sourceRepoPath: "hexbin.Rmd",
    packages: ["hexbin"],
    outputs: ["png", "svg"],
  },
  {
    id: "bubble-map-basic",
    name: "气泡地图",
    family: "空间与网络",
    description: "用气泡大小表示地理点位数值",
    kind: "bubble_map",
    icon: "map",
    galleryUrl: "https://r-graph-gallery.com/bubble-map.html",
    status: "verified",
    sourceRepoPath: "bubble-map.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "choropleth-basic",
    name: "分区着色图",
    family: "空间与网络",
    description: "按多边形区域数值进行分区着色",
    kind: "choropleth",
    icon: "map",
    galleryUrl: "https://r-graph-gallery.com/choropleth-map.html",
    status: "verified",
    sourceRepoPath: "choropleth-map.Rmd",
    packages: ["sf", "ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "density2d-basic-ggplot2",
    name: "二维密度图",
    family: "趋势与关系",
    description: "用等高线展示两个数值变量的密度",
    kind: "density2d",
    icon: "matrix",
    galleryUrl: "https://r-graph-gallery.com/2d-density-chart.html",
    status: "verified",
    sourceRepoPath: "density-2d.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "arc-basic",
    name: "弧线关系图",
    family: "空间与网络",
    description: "沿一条基线展示节点之间的连接",
    kind: "arc",
    icon: "network",
    galleryUrl: "https://www.data-to-viz.com/graph/arc.html",
    status: "verified",
    sourceRepoPath: "arc-diagram.Rmd",
    packages: [],
    outputs: ["png", "svg"],
  },
  {
    id: "edge-bundling-basic",
    name: "边捆绑关系图",
    family: "空间与网络",
    description: "用弧线聚合相近的关系边",
    kind: "edge_bundling",
    icon: "network",
    galleryUrl: "https://r-graph-gallery.com/hierarchical-edge-bundling.html",
    status: "verified",
    sourceRepoPath: "edge-bundling.Rmd",
    packages: [],
    outputs: ["png", "svg"],
  },
  {
    id: "stacked-area-basic-ggplot2",
    name: "堆叠面积图",
    family: "趋势与关系",
    description: "展示多个类别随时间的累计变化",
    kind: "stacked_area",
    icon: "line",
    galleryUrl: "https://r-graph-gallery.com/stacked-area-graph.html",
    status: "verified",
    sourceRepoPath: "stacked-area-chart.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "streamchart-basic-ggplot2",
    name: "流图",
    family: "趋势与关系",
    description: "以平滑流带展示组成变化趋势",
    kind: "streamchart",
    icon: "line",
    galleryUrl: "https://r-graph-gallery.com/streamgraph.html",
    status: "verified",
    sourceRepoPath: "streamgraph.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "circular-packing-basic",
    name: "圆形打包图",
    family: "组成",
    description: "用嵌套圆形展示层级和规模",
    kind: "circular_packing",
    icon: "matrix",
    galleryUrl: "https://r-graph-gallery.com/circle-packing.html",
    status: "verified",
    sourceRepoPath: "circular-packing.Rmd",
    packages: [],
    outputs: ["png", "svg"],
  },
  {
    id: "time-series-basic-ggplot2",
    name: "时间序列图",
    family: "趋势与关系",
    description: "按日期展示连续变化趋势",
    kind: "time_series",
    icon: "line",
    galleryUrl: "https://r-graph-gallery.com/time-series.html",
    status: "verified",
    sourceRepoPath: "time-series.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "connection-basic",
    name: "连接图",
    family: "空间与网络",
    description: "在两个节点集合之间展示连接关系",
    kind: "connection",
    icon: "network",
    galleryUrl: "https://r-graph-gallery.com/connection-map.html",
    status: "verified",
    sourceRepoPath: "connection.Rmd",
    packages: [],
    outputs: ["png", "svg"],
  },
  {
    id: "cartogram-basic",
    name: "方格统计地图",
    family: "空间与网络",
    description: "用等面积方格表达区域数值，适合比较而非地理导航",
    kind: "cartogram",
    icon: "map",
    galleryUrl: "https://r-graph-gallery.com/cartogram.html",
    status: "verified",
    sourceRepoPath: "cartogram.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "dotplot-basic-ggplot2",
    name: "点图",
    family: "基础比较",
    description: "用点的位置紧凑比较类别数值",
    kind: "dotplot",
    icon: "bar",
    galleryUrl: "https://r-graph-gallery.com/barplot.html",
    status: "verified",
    sourceRepoPath: "dot-plot.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "cleveland-basic-ggplot2",
    name: "Cleveland 点图",
    family: "基础比较",
    description: "并列比较两组类别数值",
    kind: "cleveland",
    icon: "bar",
    galleryUrl: "https://r-graph-gallery.com/lollipop-plot.html",
    status: "verified",
    sourceRepoPath: "cleveland-plot.Rmd",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "volcano-basic-ggplot2",
    name: "火山图",
    family: "高级图",
    description: "同时展示差异倍数与显著性",
    kind: "volcano",
    icon: "scatter",
    galleryUrl: "https://r-graph-gallery.com/index.html",
    status: "verified",
    sourceRepoPath: "app-template/volcano-basic-ggplot2",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "ma-basic-ggplot2",
    name: "MA 图",
    family: "高级图",
    description: "查看表达量与差异倍数的关系",
    kind: "ma",
    icon: "scatter",
    galleryUrl: "https://r-graph-gallery.com/index.html",
    status: "verified",
    sourceRepoPath: "app-template/ma-basic-ggplot2",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "pca-basic-ggplot2",
    name: "PCA 图",
    family: "高级图",
    description: "用主成分展示样本间的整体差异",
    kind: "pca",
    icon: "scatter",
    galleryUrl: "https://r-graph-gallery.com/index.html",
    status: "verified",
    sourceRepoPath: "app-template/pca-basic-ggplot2",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "forest-basic-ggplot2",
    name: "森林图",
    family: "高级图",
    description: "展示估计值及其置信区间",
    kind: "forest",
    icon: "line",
    galleryUrl: "https://r-graph-gallery.com/index.html",
    status: "verified",
    sourceRepoPath: "app-template/forest-basic-ggplot2",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "enrichment-dotplot-ggplot2",
    name: "富集分析气泡图",
    family: "高级图",
    description: "同时展示通路比例、显著性与命中基因数",
    kind: "enrichment",
    icon: "scatter",
    galleryUrl: "https://r-graph-gallery.com/index.html",
    status: "verified",
    sourceRepoPath: "app-template/enrichment-dotplot-ggplot2",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
  {
    id: "km-survival-ggplot2",
    name: "Kaplan–Meier 生存曲线",
    family: "高级图",
    description: "展示生存概率、删失和分组差异",
    kind: "survival",
    icon: "line",
    galleryUrl: "https://r-graph-gallery.com/index.html",
    status: "verified",
    sourceRepoPath: "app-template/km-survival-ggplot2",
    packages: ["survival", "ggplot2", "scales"],
    outputs: ["png", "svg"],
  },
  {
    id: "gsea-curve-ggplot2",
    name: "GSEA 富集曲线",
    family: "高级图",
    description: "展示基因集在排序列表中的运行富集分数",
    kind: "gsea",
    icon: "line",
    galleryUrl: "https://r-graph-gallery.com/index.html",
    status: "verified",
    sourceRepoPath: "app-template/gsea-curve-ggplot2",
    packages: ["ggplot2"],
    outputs: ["png", "svg"],
  },
];

const legacyChartTemplates: ChartTemplate[] = [
  ["bar", "柱状图", "基础比较", "比较分类数值", "bar"],
  ["grouped_bar", "分组柱状图", "基础比较", "比较多个分组", "bar"],
  ["stacked_bar", "堆叠柱状图", "基础比较", "展示总量与构成", "stacked_bar"],
  ["lollipop", "棒棒糖图", "基础比较", "简洁展示排名", "lollipop"],
  ["cleveland", "克利夫兰点图", "基础比较", "比较两组数值", "lollipop"],
  ["dotplot", "点图", "基础比较", "紧凑比较类别", "dot"],
  ["line", "折线图", "趋势与关系", "展示随时间变化", "line"],
  ["area", "面积图", "趋势与关系", "突出累计趋势", "area"],
  ["scatter", "散点图", "趋势与关系", "观察两变量关系", "scatter"],
  ["bubble", "气泡图", "趋势与关系", "第三变量用大小表示", "bubble"],
  ["connected_scatter", "连线散点图", "趋势与关系", "展示变化路径", "line"],
  ["regression", "回归散点图", "趋势与关系", "含趋势线", "regression"],
  ["slope", "斜率图", "趋势与关系", "比较前后变化", "line"],
  ["histogram", "直方图", "分布", "查看数值分布", "histogram"],
  ["density", "密度图", "分布", "平滑观察分布", "density"],
  ["boxplot", "箱线图", "分布", "比较各组分布", "boxplot"],
  ["violin", "小提琴图", "分布", "展示分布形状", "violin", "violin"],
  ["ridgeline", "山脊图", "分布", "多组分布对比", "density"],
  ["beeswarm", "蜂群图", "分布", "显示每一个数据点", "stripchart"],
  ["pie", "饼图", "组成", "展示少量类别占比", "pie"],
  ["donut", "环形图", "组成", "展示占比且留出中心说明", "pie"],
  ["waffle", "华夫图", "组成", "以格子展示比例", "pie"],
  ["treemap", "矩形树图", "组成", "展示层级占比", "bar"],
  ["heatmap", "热图", "矩阵与层级", "颜色编码数值矩阵", "heatmap"],
  ["correlogram", "相关性矩阵", "矩阵与层级", "展示变量相关关系", "heatmap"],
  ["dendrogram", "树状图", "矩阵与层级", "查看层级聚类", "dendrogram"],
  ["upset", "UpSet 图", "矩阵与层级", "比较集合交集", "bar"],
  ["map", "地图", "空间与网络", "地理数据可视化", "scatter"],
  ["network", "网络图", "空间与网络", "节点与连线关系", "network"],
  ["sankey", "桑基图", "空间与网络", "展示流向", "bar"],
  ["chord", "弦图", "空间与网络", "展示群组间关系", "bar"],
  ["radar", "雷达图", "高级图", "多维指标轮廓", "radar"],
  ["parallel", "平行坐标图", "高级图", "比较多指标记录", "parallel"],
  ["venn", "韦恩图", "高级图", "比较 2–3 个集合", "venn"],
  ["alluvial", "河流图", "高级图", "追踪分类流动", "bar"],
  ["circular_bar", "环形柱状图", "高级图", "径向展示排名", "bar"],
].map(([id, name, family, description, kind, needs]) => ({
  id,
  name,
  family: family as ChartFamily,
  description,
  kind,
  needs: needs as unknown as string[] | undefined,
  icon: iconFor(kind),
  galleryUrl: galleryUrlFor(kind),
  // 旧目录仅供兼容；完成逐模板视觉回归前不会标记为 verified。
  status: "draft" as const,
  packages: ["jsonlite"],
  outputs: ["png", "svg"] as ChartOutputFormat[],
}));

/** 所有已验证模板共用同一套投稿输出设备；具体设备由运行时按需打开。 */
const publicationOutputs: ChartOutputFormat[] = ["png", "tiff", "svg", "pdf", "eps"];
export const chartTemplates = [...officialTemplates, ...legacyChartTemplates].map(
  (template) => ({ ...template, outputs: publicationOutputs }),
);
export const verifiedChartTemplates = chartTemplates.filter(
  (template) => template.status === "verified",
);
/** 旧版参数 ID 到已验证独立模板的迁移映射。 */
export const legacyTemplateMigration: Record<string, string> = {
  bar: "bar-basic-ggplot2",
  grouped_bar: "grouped-bar-basic-ggplot2",
  stacked_bar: "stacked-bar-basic-ggplot2",
  lollipop: "lollipop-basic-ggplot2",
  cleveland: "cleveland-basic-ggplot2",
  dotplot: "dotplot-basic-ggplot2",
  line: "line-basic-ggplot2",
  area: "area-basic-ggplot2",
  scatter: "scatter-basic-ggplot2",
  bubble: "bubble-basic-ggplot2",
  connected_scatter: "connected-scatter-basic-ggplot2",
  regression: "regression-basic-ggplot2",
  slope: "slope-basic-ggplot2",
  histogram: "histogram-basic-ggplot2",
  density: "density-basic-ggplot2",
  boxplot: "boxplot-basic-ggplot2",
  violin: "violin-basic-ggplot2",
  ridgeline: "ridgeline-basic",
  beeswarm: "beeswarm-basic",
  pie: "pie-basic-ggplot2",
  donut: "donut-basic-ggplot2",
  waffle: "waffle-basic",
  treemap: "treemap-basic",
  heatmap: "heatmap-basic-ggplot2",
  correlogram: "correlogram-basic-ggplot2",
  dendrogram: "dendrogram-basic-ggplot2",
  upset: "upset-basic",
  map: "map-points-basic-ggplot2",
  network: "network-basic-ggplot2",
  sankey: "sankey-basic-ggplot2",
  chord: "chord-basic-ggplot2",
  radar: "radar-basic-ggplot2",
  parallel: "parallel-basic-ggplot2",
  venn: "venn-basic",
  alluvial: "alluvial-basic",
  circular_bar: "circular-bar-basic-ggplot2",
};

export const demoData = `group,value,value2,size\nControl,12,9,4\nTreatment A,18,15,8\nTreatment B,24,22,12\nTreatment C,16,19,6\nTreatment D,28,25,10`;
